spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microserviceCloudConfigClient
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/2

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microserviceCloudConfigClient
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com7001/eureka/ 

